### ISSUE TITLE
Update prevented by sortable issue

### ISSUE THREAD

**Issue by dillingham** [Naxon/nova-field-sortable#16]
nova 1.2.1 / latest chrome

When I try to update a resource with this field I get the following in the console
Seems like its checking validation

![weird-issue](https://user-images.githubusercontent.com/29180903/50465119-1fb6d980-0963-11e9-8b80-d9efa6e42a18.PNG)

**Comment by FaridAghili** [comment]
Same here

**Comment by jBOKA** [comment]
I can see it too.
You need to hide the field in detail (maybe not necessary) and form. Only use it on index.

As far as I can see, this should be default behaviour, since the ordering should not happen on single instance editing. At least that's what the underlying eloquent trait suggests.

Just add ònlyOnIndex()` to your field definition.

@Naxon if you agree, can you make the field actually do nothing in a form, or at least prevent the nova error, since it crashes the update functionality and these kind of bugs clutter up the nova issue repo.

Thanks for the field btw, works smoothly.

**Comment by dillingham** [comment]
you can use my fork since this has been abandoned

```
        "naxon/nova-field-sortable": "dev-fixed-master", 
```
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/dillingham/nova-field-sortable"
        }
    ],
```

**Comment by jBOKA** [comment]
That's pretty straightforward. Alright
